export enum EDITOR_ACTIONS {
  UPDATE_TEXT_NODE = 'UPDATE_TEXT_NODE',
  ADD_TEXT_NODE = 'ADD_TEXT_NODE',
  REMOVE_TEXT_NODE = 'REMOVE_TEXT_NODE',
  MOVE_TEXT_NODE = 'MOVE_TEXT_NODE',
  RESIZE_TEXT_NODE = 'RESIZE_TEXT_NODE',
}
